### ISSUE TITLE
TV-Dataport: "Tier Allowance" is displayed as "Yes" by default but not calculated

### ISSUE THREAD

**Issue by ruvox** [Tekergo-T/TVData#10]
For any specific income calculation, the tier allowance should be considered, if the related toggle button `dataport-tier-allowance` is set to "Yes". This button is set to "Yes" by default.
Initially, while the button is set to "Yes" and the tier allowance is displayed under "Income and Taxation Summary", it is not taken into account for the calculation. It is not added towards the "Salary Before Taxes".
A recalculation with a click on the `calculateIncome` button does also not solve this. 
Once the toggle button `dataport-tier-allowance` is set to "No" and then back to "Yes" and another recalculation is done, the tier allowance is not only displayed but also taken into account for the calculation.

**Comment by Tekergo-T** [comment]
Nice catch. I fixed the issue.
