### ISSUE TITLE
Request: Add a FAQ/tutorial for how once can test their contribution

### ISSUE THREAD

**Issue by lyrad87** [Tekergo-T/TVData#3]
Hi there, love the project but I have no idea how I could test my changes. Could you please add a tutorial or FAQ for this? Or I just submit a PR once I think I’m done. I’d prefer to test it locally first though. Thanks in advance!

**Comment by Tekergo-T** [comment]
Feel free to make your changes through a pull request. I will carry out an integration test and in case there are some mistakes I will fix it. Thank you. 

I will add some clarification in the future about the integration test.
