### ISSUE TITLE
Default option not applied

### ISSUE THREAD

**Issue by lyrad87** [Tekergo-T/TVData#7]
I've had a [PR](https://github.com/Tekergo-T/TVData/pull/5) that changed the default option of the Entgeltgruppenzulagen to "yes" but when I check it on the site, the default still seems to be "no".

**Comment by Tekergo-T** [comment]
My PC got broken and I haven't been able to check the integration yet.

**Comment by Tekergo-T** [comment]
I updated to your latest change.
